name: Build and deploy (main → gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # gh-pages 푸시용

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.90.0
      GO_VERSION: 1.24.5
      HUGO_VERSION: 0.148.2
      NODE_VERSION: 22.18.0
      TZ: Asia/Seoul

    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dart Sass
        run: |
          curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          mkdir -p "$HOME/.local"
          tar -C "$HOME/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          echo "$HOME/.local/dart-sass" >> "$GITHUB_PATH"

      - name: Install Hugo
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          mkdir -p "$HOME/.local/hugo"
          tar -C "$HOME/.local/hugo" -xf "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "$HOME/.local/hugo" >> "$GITHUB_PATH"

      - name: Verify tools
        run: |
          echo "Sass: $(sass --version)"
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
          echo "Node: $(node --version)"

      - name: Install Node deps (optional)
        run: |
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config core.quotepath false

      - name: Prepare gh-pages worktree
        run: |
          # 깨끗한 public 준비
          rm -rf public
          mkdir -p public
          git worktree prune
          rm -rf .git/worktrees/public/ || true

          # 원격에 gh-pages 없으면 orphan으로 초기화
          if ! git ls-remote --exit-code --heads origin gh-pages >/dev/null 2>&1; then
            echo "Initializing orphan gh-pages branch"
            tmpdir=$(mktemp -d)
            pushd "$tmpdir" >/dev/null
            git init
            git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
            git checkout --orphan gh-pages
            : > .gitignore
            git add .gitignore
            git commit -m "Initialize gh-pages"
            git push -u origin gh-pages
            popd >/dev/null
          else
            git fetch origin gh-pages
          fi

          echo "Attach gh-pages to public/ via worktree"
          git worktree add -B gh-pages public origin/gh-pages

      - name: Build site into public (worktree)
        run: |
          env HUGO_ENV="production" \
          hugo \
            --gc \
            --minify \
            --baseURL "https://seungyeah.github.io/" \
            -t github-style \
            --destination public

          # GitHub Pages에서 언더스코어 파일 무시 방지
          touch public/.nojekyll

      - name: Commit & push to gh-pages
        run: |
          cd public
          git add --all
          if git diff --cached --quiet; then
            echo "No changes to publish."
            exit 0
          fi
          git commit -m "Publish (CI) ${GITHUB_SHA}"
          git push origin gh-pages
